version: '3'

networks:
  default:
  #external:
  # name: nginx-proxy

volumes:
  timeoff-prod-db:
  timeoff-prod-config:
  timeoff-dev-db:
  timeoff-dev-config:

services:

### PRODUCTION MAKE BUILD ##############################################
  timeoff:
      image: timeoff-management-prod
      build:
          context: "./"
          dockerfile: "Dockerfile"
      container_name: 'timeoff_app_production'
      volumes:
        - timeoff-prod-config:/app/timeoff-management/config
        - timeoff-prod-db:/app/timeoff-management/data/
      ports:
        - "3090:3000"
      environment:
        NODE_ENV: production
        ALLOW_ACCOUNTS_CREATION: 'true'  # set this to false to disable public account creation (set it once you have created your company to disable public regitration)
        PROMOTION_URL: https://example.com  # uncomment and set this if you want to use you URL for footer promotion url
        # SENDER_MAIL: timeoff@example.com # only set this if you want mail support
        # SMTP_HOST: 127.0.0.1
        # SMTP_PORT: 25
        # SMTP_USER: timeoff
        # SMTP_PASSWORD: timeoff
        APP_URL: example.com
#        VIRTUAL_HOST: example.com
#        LETSENCRYPT_HOST: example.com
#        LETSENCRYPT_EMAIL: timeoff@example.com
      
### DEVELOPMENT MAKE BUILD ##############################################
  timeoff_dev: 
      image: timeoff-management-dev
      build:
          context: "./"
          dockerfile: "Dockerfile"
      container_name: 'timeoff_app_dev'
      volumes:
      - timeoff-dev-config:/app/timeoff-management/config
      - timeoff-dev-db:/var/lib/mysql
      ports:
        - "3091:3000"
      environment:
        #NODE_ENV: development
        ALLOW_ACCOUNTS_CREATION: 'true'  # set this to false to disable public account creation (set it once you have created your company to disable public regitration)
        # PROMOTION_URL: https://timeoff.example.com # uncomment and set this if you want to use you URL for footer promotion url 
        # SENDER_MAIL: timeoff@example.com # only set this if you want mail support
        # SMTP_HOST: 127.0.0.1
        # SMTP_PORT: 25
        # SMTP_USER: timeoff
        # SMTP_PASSWORD: timeoff
        APP_URL: example.com
#        VIRTUAL_HOST: example.com
#        LETSENCRYPT_HOST: example.com
#        LETSENCRYPT_EMAIL: timeoff@example.com

